# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(null=True)),
                ('blocked_at', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('follow_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tweet.Account')),
                ('followed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tweet.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(null=True)),
                ('retweet_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet.Tweet')),
                ('tweet_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet.Account')),
            ],
        ),
    ]
