# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20171120_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow_from',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followed_by',
        ),
        migrations.AddField(
            model_name='account',
            name='follows',
            field=models.ManyToManyField(related_name='_account_follows_+', to='tweet.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet.Tweet'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
