# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20171123_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', related_query_name='tweet', to='tweet.Account'),
        ),
    ]
